# Generated by Django 2.1.7 on 2019-02-25 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisTasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('summary', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('team', models.CharField(max_length=50)),
                ('application', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DevTasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('summary', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('team', models.CharField(max_length=50)),
                ('application', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='JIRA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='JIRAUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=30)),
                ('displayName', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='TestTasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('summary', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('team', models.CharField(max_length=50)),
                ('application', models.CharField(max_length=50)),
            ],
        ),
    ]
