# Generated by Django 2.1.7 on 2019-02-25 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jira_sub_tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnaDocTasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('summary', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('team', models.CharField(max_length=50)),
                ('application', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DevDocTasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('summary', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('team', models.CharField(max_length=50)),
                ('application', models.CharField(max_length=50)),
            ],
        ),
    ]
