# Generated by Django 2.1.7 on 2019-02-25 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jira_sub_tasks', '0003_anadevdoctasks'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnaDevDocTasks',
        ),
    ]
