# Generated by Django 2.1.7 on 2019-02-28 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jira_sub_tasks', '0007_anadod_devanadod_devdod'),
    ]

    operations = [
        migrations.CreateModel(
            name='JIRALabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('jiraLabel', models.CharField(max_length=50)),
            ],
        ),
    ]
