# Generated by Django 2.1.7 on 2019-02-28 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jira_sub_tasks', '0008_jiralabel'),
    ]

    operations = [
        migrations.CreateModel(
            name='JiraApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AppName', models.CharField(max_length=20)),
                ('AppDesc', models.CharField(max_length=50)),
                ('AppHomeUrl', models.CharField(max_length=100)),
                ('AppId', models.CharField(max_length=10)),
            ],
        ),
    ]
