# Generated by Django 2.1.7 on 2019-02-28 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jira_sub_tasks', '0009_jiraapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='jiraapp',
            name='AppDashUrl',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
