# Generated by Django 2.1.7 on 2019-03-02 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jira_sub_tasks', '0011_devtasks_hours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anadod',
            name='mandatory',
        ),
        migrations.RemoveField(
            model_name='anador',
            name='mandatory',
        ),
        migrations.RemoveField(
            model_name='devanadod',
            name='mandatory',
        ),
        migrations.RemoveField(
            model_name='devanador',
            name='mandatory',
        ),
        migrations.RemoveField(
            model_name='devdod',
            name='mandatory',
        ),
        migrations.RemoveField(
            model_name='devdor',
            name='mandatory',
        ),
    ]
