# Generated by Django 2.1.7 on 2019-03-04 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jira_sub_tasks', '0014_jirausers_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnaDocTasks',
        ),
        migrations.DeleteModel(
            name='DevDocTasks',
        ),
    ]
