# Generated by Django 2.1.7 on 2019-03-07 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jira_sub_tasks', '0015_auto_20190305_0103'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=30)),
                ('value', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='jiraapp',
            name='AppDashTooltip',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='jiraapp',
            name='AppHomeTooltip',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
