# Generated by Django 2.1.7 on 2019-03-16 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jira_sub_tasks', '0017_backlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClarifyAnalysisTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('summary', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('team', models.CharField(max_length=50)),
                ('application', models.CharField(max_length=50)),
                ('hours', models.CharField(blank=True, max_length=10, null=True)),
                ('hoursDesc', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClarifyApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AppName', models.CharField(max_length=20)),
                ('AppDesc', models.CharField(max_length=50)),
                ('AppHomeUrl', models.CharField(max_length=100)),
                ('AppHomeTooltip', models.CharField(blank=True, max_length=50, null=True)),
                ('AppId', models.CharField(max_length=10)),
                ('AppDashUrl', models.CharField(max_length=250)),
                ('AppDashTooltip', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClarifyAppInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=30)),
                ('value', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ClarifyDevTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('summary', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('team', models.CharField(max_length=50)),
                ('application', models.CharField(max_length=50)),
                ('hours', models.CharField(blank=True, max_length=10, null=True)),
                ('hoursDesc', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClarifyDoD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('checked', models.CharField(max_length=10)),
                ('option', models.CharField(max_length=10)),
                ('id_1', models.CharField(max_length=10)),
                ('rank', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ClarifyDoR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('checked', models.CharField(max_length=10)),
                ('option', models.CharField(max_length=10)),
                ('id_1', models.CharField(max_length=10)),
                ('rank', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ClarifyLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('jiraLabel', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ClarifyTestTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('summary', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('team', models.CharField(max_length=50)),
                ('application', models.CharField(max_length=50)),
                ('hours', models.CharField(blank=True, max_length=10, null=True)),
                ('hoursDesc', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClarifyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=30)),
                ('displayName', models.CharField(max_length=150)),
                ('role', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
