# Generated by Django 2.1.7 on 2019-03-17 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jira_sub_tasks', '0019_team'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Team',
        ),
    ]
