# Generated by Django 2.1.7 on 2019-03-17 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jira_sub_tasks', '0022_auto_20190317_0641'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnaDOD',
        ),
        migrations.DeleteModel(
            name='AnaDOR',
        ),
        migrations.DeleteModel(
            name='ClarifyAnalysisTask',
        ),
        migrations.DeleteModel(
            name='ClarifyApp',
        ),
        migrations.DeleteModel(
            name='ClarifyAppInfo',
        ),
        migrations.DeleteModel(
            name='ClarifyDevTask',
        ),
        migrations.DeleteModel(
            name='ClarifyDoD',
        ),
        migrations.DeleteModel(
            name='ClarifyDoR',
        ),
        migrations.DeleteModel(
            name='ClarifyLabel',
        ),
        migrations.DeleteModel(
            name='ClarifyTestTask',
        ),
        migrations.DeleteModel(
            name='ClarifyUser',
        ),
        migrations.DeleteModel(
            name='DevAnaDOD',
        ),
        migrations.DeleteModel(
            name='DevAnaDOR',
        ),
        migrations.AddField(
            model_name='devdod',
            name='team',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='devdor',
            name='team',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='jiraapp',
            name='team',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='jiralabel',
            name='team',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='jirausers',
            name='team',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='analysistasks',
            name='team',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='devtasks',
            name='team',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='testtasks',
            name='team',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
