# Generated by Django 2.1.7 on 2019-03-17 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jira_sub_tasks', '0023_auto_20190317_0836'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysistasks',
            name='jteam',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='devtasks',
            name='jteam',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='testtasks',
            name='jteam',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
