# Generated by Django 2.1.7 on 2019-03-18 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jira_sub_tasks', '0024_auto_20190317_0857'),
    ]

    operations = [
        migrations.CreateModel(
            name='JiraStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=50)),
                ('team', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
