# Generated by Django 2.1.7 on 2019-03-27 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jira_sub_tasks', '0025_jirastatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='jiralabel',
            name='sub_type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
