# Generated by Django 2.1.7 on 2019-03-27 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jira_sub_tasks', '0026_jiralabel_sub_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jiralabel',
            name='sub_type',
        ),
    ]
