# Generated by Django 2.1.7 on 2019-03-27 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jira_sub_tasks', '0027_remove_jiralabel_sub_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jiralabel',
            name='type',
            field=models.CharField(max_length=50),
        ),
    ]
